### ISSUE TITLE
Reuse http.Client instead create for each request

### ISSUE THREAD

**Issue by OmidHekayati** [aliworkshop/samanpayment#1]
Usually, bank SDK use many times in a few time periods, So we must reuse TCP || TCP/TLS connection to the bank server. Do you have any plans to fix this problem in the codes?

However, I strongly argue that `net/http` package has bad architecture and use high resource for such a simple task.

**Comment by OmidHekayati** [comment]
However, GO compiler has enough intelligence to improve the performance of code in below link, But it is your responsibility to write better code by move `local var` in a `func` to `global unexported var` when it uses like a `const` just by moving it to outside of a `func`.

https://github.com/aliworkshop/samanpayment/blob/master/saman.go#L129

**Comment by aliworkshop** [comment]
> However, GO compiler has enough intelligence to improve the performance of code in below link, But it is your responsibility to write better code by move `local var` in a `func` to `global unexported var` when it uses like a `const` just by moving it to outside of a `func`.
> 
> https://github.com/aliworkshop/samanpayment/blob/master/saman.go#L129

your suggestion was applied to version 1.1
regards

**Comment by aliworkshop** [comment]
> Usually, bank SDK use many times in a few time periods, So we must reuse TCP || TCP/TLS connection to the bank server. Do you have any plans to fix this problem in the codes?
> 
> However, I strongly argue that `net/http` package has bad architecture and use high resource for such a simple task.

actually you can fork the package and send your solution as pull request.
i'll apply your code in package if it is good. it's a pleasure! :)
